SCSDN/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('blog.urls', namespace='blog')),
    re_path(r'accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'articles/', include('articles.urls', namespace='articles')),
    re_path(r'^mdeditor/', include('mdeditor.urls', namespace='mdeditor')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page=reverse_lazy('blog:index')), name='logout'),
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    path('reset/<uidb64>/<token>/', views.ResetPasswordView.as_view(), name='reset'),
    re_path(r'^change/$', views.ChangePasswordView.as_view(), name='change'),
    re_path(r'^send_email/$', views.SendEmailView.as_view(), name='send_email'),

    re_path(r'^user-center-info/$', views.UserCenterInfoView.as_view(), name='uc_info'),
    re_path(r'^user-center-collects/$', views.UserCenterCollectsView.as_view(), name='uc_collects'),
    re_path(r'^user-center-focus/$', views.UserCenterFocusView.as_view(), name='uc_focus'),
    re_path(r'^user-center-fans/$', views.UserCenterFansView.as_view(), name='uc_fans'),

    re_path(r'^user-center-photos/$', views.UserCenterPhotosView.as_view(), name='uc_photos'),
    re_path(r'^user-center-news/$', views.UserCenterNewsView.as_view(), name='uc_news'),

    re_path(r'^user-center-edit-protrait/$', views.UserCenterEditProtraitView.as_view(), name='uc_edit_protrait'),
    re_path(r'^user-center-edit-info/$', views.UserCenterEditInfoView.as_view(), name='uc_edit_info'),

    re_path(r'^accounts-manager-info/$', views.AccountsManagerInfoView.as_view(), name='am_info'),
]

apps/articles/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from articles import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^search/$', views.ArticleSearchView.as_view(), name='search'),
    re_path(r'^list/$', views.ArticleBackListView.as_view(), name='back'),
    re_path(r'^column/$', views.ArticleBackListView.as_view(), name='columns'),
    re_path(r'^tags/$', views.ArticleBackListView.as_view(), name='tags'),
    re_path(r'^comments/$', views.CommentsPostView.as_view(), name='comments'),
    re_path(r'^list/(?P<username>\w+)/$', views.ArticleListView.as_view(), name='list'),
    re_path(r'^show/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ArticleShowView.as_view(), name='show'),
    re_path(r'^actions/$', views.ArticleActionsView.as_view(), name='actions'),
    re_path(r'^post/$', views.ArticlePostView.as_view(), name='post')
]

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
from django.utils.translation import gettext as _

from datetime import datetime


# Create your models here.

# TODO: 用户信息表
class UserProfile(AbstractUser):
    SEXES = (
        ('male', '男'),
        ('female', '女'),
    )
    nick_name = models.CharField(max_length=50, blank=True, null=True, verbose_name='昵称')
    birth = models.DateField(blank=True, null=True, verbose_name='生日')
    phone = models.CharField(max_length=200, blank=True, null=True, unique=True, verbose_name='电话')
    gender = models.CharField(max_length=6, choices=SEXES, default='male', verbose_name='性别')
    profession = models.CharField(max_length=200, blank=True, null=True, verbose_name='职业')
    company = models.CharField(max_length=200, blank=True, null=True, verbose_name='公司')
    school = models.CharField(max_length=200, blank=True, null=True, verbose_name='学校')
    intro = models.TextField(blank=True, null=True, verbose_name='个人简介')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='/static/common/imgs/avatar.png', blank=True,
                              null=True, verbose_name='头像')

    class Meta:
        db_table = 'userprofile'
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name
        ordering = ['-date_joined']

    def __str__(self):
        return _('username') + ':{0}'.format(self.username)

    def age(self):
        return None if not self.birth else round(((datetime.now().date() - self.birth).days) / 365)

    def name(self):
        return self.get_full_name()

    def set_fans(self, fans):
        relationship = UserRelation.objects.get_or_create(focus=self, fans=fans)
        return relationship

    def set_unfollow(self, focus):
        relationship = UserRelation.objects.get(focus=focus, fans=self)
        if relationship:
            relationship.delete()
        return True

    def get_fans(self):
        return [relationship.fans for relationship in self.fans.all()]

    def get_focus(self):
        return [relationship.focus for relationship in self.focus.all()]

    def get_origin(self):
        # 原创文章
        return self.articles.filter(status__in=['1', '2'])

    age.short_description = '年龄'
    name.short_description = '姓名'
    age = property(age)
    name = property(name)


# TODO: 用户关系表
class UserRelation(models.Model):
    focus = models.ForeignKey(UserProfile, related_name='fans', on_delete=models.CASCADE, verbose_name='关注')
    fans = models.ForeignKey(UserProfile, related_name='focus', on_delete=models.CASCADE, verbose_name='粉丝')

    class Meta:
        db_table = 'userrelation'
        verbose_name = '用户关系'
        verbose_name_plural = verbose_name
        unique_together = ('focus', 'fans')

    def __str__(self):
        return '关注:{0} 粉丝:{1}'.format(self.focus, self.fans)

apps/accounts/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django import forms
from django.db.models import Q
from django.forms import widgets
from django.contrib.admin import widgets as admin_widgets
from django.conf import settings
from django.core import mail
from django.core.cache import cache
from django.contrib.auth import (authenticate, password_validation, get_user_model)
from django.utils.translation import gettext, gettext_lazy as _
from django.contrib.auth.forms import UsernameField, AuthenticationForm

# 由于定制了用户管理模块，所以不能直接使用auth.models.User模型
User = get_user_model()


# TODO：登录表单
class AccountsLoginForm(AuthenticationForm):
    '''
        登录表单
    '''
    username = UsernameField(max_length=200, label='用户名', widget=widgets.TextInput(
        attrs={
            'type': 'text',
            'class': 'form-control',
            'title': '请输入用户名、手机或者邮箱地址',
            'autocomplete': 'off',
            "autofocus": "autofocus",
            'placeholder': '用户名 | 手机 | 邮箱',
            "oninvalid": "setCustomValidity('用户名不能为空哟')",
            "oninput": "setCustomValidity('')"
        }))
    password = forms.CharField(label='密码', widget=widgets.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control',
            'title': '请输入密码',
            'autocomplete': 'off',
            'placeholder': '密码',
            'onblur': 'var index = parent.layer.getFrameIndex(window.name);$(".alert-danger").remove("");parent.layer.style(index, {height: "496px"});',
            "oninvalid": "setCustomValidity('密码不能为空哟')",
            "oninput": "setCustomValidity('')"
        }))

    remember = forms.BooleanField(label='下次自动登录', required=False)

    verify = forms.CharField(max_length=10, required=False, label='验证码', widget=widgets.TextInput(
        attrs={
            'type': 'text',
            'class': 'form-control',
            'autocomplete': 'off',
            'title': '请输入验证码',
            'placeholder': '验证码',
            "oninvalid": "setCustomValidity('请输入验证码')",
            "oninput": "setCustomValidity('')"
        }))

    def clean(self):
        self.cleaned_data.get('remember')
        self.cleaned_data.get('verify')
        super(AccountsLoginForm, self).clean()
        return self.cleaned_data

    def clean_username(self):
        """函数功能.
            用户验证
        Args:
            self (object): 表单实例

        Returns:
            username: str
        """
        username = self.cleaned_data['username']
        auth_user = User.objects.filter(Q(username=username) | Q(email=username) | Q(phone=username))
        if username and auth_user:
            return auth_user[0].username
        else:
            raise forms.ValidationError('用户名不存在')

    def clean_password(self):
        """函数功能.
            密码验证
        Args:
            self (object): 表单实例

        Returns:
            password: str
        """
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        self.user_cache = authenticate(self.request, username=username, password=password)
        if self.user_cache is None:
            raise forms.ValidationError('密码和用户名不匹配')
        return password

    def clean_remember(self):
        """函数功能.
            通过session实现下次自动登录，
            remember=True，设置session保存周期为settings.SESSION_COOKIE_AGE
            remember=False，设置session保存周期为0，即退出浏览器清楚
        Args:
            self (object): 表单实例

        Returns:
            remember: Boolean
        """
        remember = self.cleaned_data.get('remember', False)
        if remember:
            self.request.session.set_expiry(None)
        else:
            self.request.session.set_expiry(0)
        return remember

    def clean_verify(self):
        """函数功能.
                验证码验证
        Args:
            self (object): 表单实例

        Returns:
            verify: str
        """
        verify = self.cleaned_data.get('verify', '')
        verify_code = self.request.session.get('verify', None)
        if verify_code and verify.lower() != verify_code.lower():
            raise forms.ValidationError('请输入正确的验证码')
        return verify


# TODO：注册表单
class AccountsRegisterForm(forms.ModelForm):
    verify = forms.CharField(label='邮箱验证码', required=False, widget=widgets.TextInput(
        attrs={
            'type': 'text',
            'class': 'form-control',
            'autocomplete': 'off',
            'placeholder': '请输入邮箱验证码',
            "oninvalid": "setCustomValidity('请输入正确的邮箱验证码')",
            "oninput": "setCustomValidity('')",
            'title': '请输入您在邮箱中收到的验证码'
        }))

    class Meta:
        model = User
        fields = ('username', 'password', 'email')
        widgets = {
            'username': widgets.TextInput(
                attrs={
                    'type': 'text',
                    'class': 'form-control',
                    'autocomplete': 'off',
                    "autofocus": "autofocus",
                    'pattern': '^[a-z]+(\w)*',
                    'title': '用户名由小写的字母、数字和下划线组成。',
                    "oninvalid": "setCustomValidity('用户名由小写的字母、数字和下划线组成，并以字母开头。')",
                    "oninput": "setCustomValidity('')",
                    'placeholder': '用于登录的用户名'
                }),
            'password': widgets.PasswordInput(
                attrs={
                    'type': 'password',
                    'class': 'form-control',
                    'autocomplete': 'off',
                    'minlength': "6",
                    'title': '密码长度不低于6位。',
                    "oninvalid": "setCustomValidity('密码长度不低于6位。')",
                    "oninput": "setCustomValidity('')",
                    'placeholder': '设置您的密码'
                }),
            'email': widgets.EmailInput(
                attrs={
                    'type': 'email',
                    'class': 'form-control',
                    'autocomplete': "off",
                    'required': True,
                    # 'pattern': '^([0-9A-Za-z\-_\.]+)@([0-9a-z]+\.[a-z]{2,3}(\.[a-z]{2})?)$',
                    'title': '请输入您的邮箱账号！',
                    "oninvalid": "setCustomValidity('请输入正确的邮箱地址')",
                    "oninput": "setCustomValidity('')",
                    'placeholder': '请输入您的邮箱账号'
                })
        }
        # 定义字段label_tag
        labels = {'email': '邮箱'}

    def clean_email(self):
        """函数功能.
                验证邮箱是否被注册
        Args:
            self (object): 表单实例

        Returns:
            verify: str
        """
        email = self.cleaned_data['email']
        if email and User.objects.filter(email=email):
            raise forms.ValidationError('邮箱{0}已被注册'.format(email))
        return email

    def clean_verify(self):
        """函数功能.
                邮箱验证码验证
        Args:
            self (object): 表单实例

        Returns:
            verify: str
        """
        verify = self.cleaned_data['verify']
        try:
            email = self.cleaned_data['email']
        except Exception as e:
            raise forms.ValidationError('邮箱已经注册或邮箱地址错误！')
        if email is not None and verify.strip().lower() != cache.get(
                'register_verify_{0}'.format(email.strip().lower().split('@')[0]), '').strip().lower():
            raise forms.ValidationError('验证码错误！')
        return verify


# TODO：设置密码表单
class AccountsSetPasswordForm(forms.Form):
    password = forms.CharField(max_length=128, label="输入新密码", widget=widgets.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control',
            'autocomplete': 'off',
            'minlength': "6",
            'title': '密码长度不低于6位。',
            "oninvalid": "setCustomValidity('密码长度不低于6位。')",
            "oninput": "setCustomValidity('')",
            'placeholder': '输入新密码'
        }))
    password_ = forms.CharField(max_length=128, label="确认新密码", widget=widgets.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control',
            'autocomplete': 'off',
            'minlength': "6",
            'title': '密码长度不低于6位。',
            "oninvalid": "setCustomValidity('密码长度不低于6位。')",
            "oninput": "setCustomValidity('')",
            'placeholder': '确认新密码'
        }))
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }

    def __init__(self, user, *args, **kwargs):
        """函数功能.
                表单初始化
        Args:
            user: 通过uidb64解析获得用户信息

        Returns:
            None
        """
        self.user = user
        super().__init__(*args, **kwargs)

    def clean_password_(self):
        password = self.cleaned_data.get('password')
        password_ = self.cleaned_data.get('password_')
        if password and password_:
            if password != password_:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        password_validation.validate_password(password_, self.user)
        return password_

    def save(self, commit=True):
        password = self.cleaned_data["password"]
        self.user.set_password(password)
        if commit:
            self.user.save()
        return self.user


# TODO：修改密码表单
class AccountsChangePwdForm(AccountsSetPasswordForm):
    password_old = forms.CharField(max_length=128, label="输入旧密码", widget=widgets.PasswordInput(
        attrs={
            'type': 'password',
            'class': 'form-control',
            'autocomplete': 'off',
            'minlength': "6",
            'title': '密码长度不低于6位。',
            "oninvalid": "setCustomValidity('密码长度不低于6位。')",
            "oninput": "setCustomValidity('')",
            'placeholder': '输入旧密码'
        }))

    error_messages = {
        **AccountsSetPasswordForm.error_messages,
        'password_incorrect': _("Your old password was entered incorrectly. Please enter it again."),
    }

templates/accounts/accounts_manager_info.html
{% extends 'accounts/base/user_center_base.html' %}
{% block left_slider_body %}
    {% include 'accounts/base/accounts_manager_leftslider.html' %}
{% endblock %}
{% block left_slider_subbox %}{% endblock %}
{% block right_slider_subbox %}{% endblock %}

templates/accounts/login.html
{% extends "common/layerui.html" %}
{% load accounts %}
{% block form_body %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}" class="col-sm-12 control-label font-weight-bold">
            {{ form.username.label_tag }}
        </label>
        {% if form.username.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.username.errors }}</label>
        {% endif %}
        <div class="col-sm-12  control-label">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}" class="col-sm-12 control-label  font-weight-bold">
            {{ form.password.label_tag }}
        </label>
        {% if form.password.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.password.errors }}</label>
        {% endif %}
        <div class="col-sm-12">
            {{ form.password }}
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12">
            <div class="checkbox">
                {{ form.remember }}
                <label for="{{ form.remember.id_for_label }}">
                    {{ form.remember.label_tag }}
                </label>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-12 row">
            {% if form.verify.errors %}
                <label class="col-sm-12 control-label alert alert-danger">{{ form.verify.errors }}</label>
            {% endif %}
            <div class="col-8">
                {{ form.verify }}
            </div>
            <div class="col-4">
                <img id="id_login_verify_img" class="rounded-0" width="100px"
                     src="{{ MEDIA_URL }}verifys/verify.png"
                     title="点击刷新" onclick="RefreshVerify()">
            </div>
        </div>
    </div>
    <div class="form-group my-auto">
        <div class="col-sm-offset-2 col-sm-12 text-center">
            <button type="submit" class="btn btn-block btn-primary btn-lg">登录</button>
        </div>
    </div>
    <div class="container-fluid" style="margin-top: 15px">
        <a class="btn-link" target="_blank" href="{% url 'accounts:send_email' %}">忘记密码 ?</a>
        <a class="btn-link float-right" target="_self" href="{% url 'accounts:register' %}">新用户注册</a>
    </div>
{% endblock %}
{% block base_code_extend %}{% endblock %}

templates/accounts/register.html
{% extends "common/layerui.html" %}
{% block form_body %}
    <div class="form-group">
        <label for="{{ form.username.id_for_label }}"
               class="col-sm-12 control-label  font-weight-bold">{{ form.username.label_tag }}
        </label>
        {% if form.username.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.username.errors }}</label>
        {% endif %}
        <div class="col-sm-12">
            {{ form.username }}
        </div>
    </div>
    <div class="form-group">
        <label for="{{ form.password.id_for_label }}"
               class="col-sm-12 control-label  font-weight-bold">{{ form.password.label_tag }}
        </label>
        {% if form.password.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.password.errors }}</label>
        {% endif %}
        <div class="col-sm-12">
            {{ form.password }}
        </div>
    </div>
    {% if form.password_agin %}
        <div class="form-group">
            <label for="{{ form.password_agin.id_for_label }}"
                   class="col-sm-12 control-label  font-weight-bold">{{ form.password_agin.label_tag }}
            </label>
            {% if form.password_agin.errors %}
                <label class="col-sm-12 control-label alert alert-danger">{{ form.password_agin.errors }}</label>
            {% endif %}
            <div class="col-sm-12">
                {{ form.password_agin }}
            </div>
        </div>
    {% endif %}
    <div class="form-group">
        <label for="{{ form.email.id_for_label }}"
               class="col-sm-12 control-label  font-weight-bold">{{ form.email.label_tag }}
        </label>
        {% if form.email.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.email.errors }}</label>
        {% endif %}
        <div class="col-sm-12">
            {{ form.email }}
        </div>
    </div>
    <div class="form-group" style="display: none" id="id_verify_box">
        {% if form.verify.errors %}
            <label class="col-sm-12 control-label alert alert-danger">{{ form.verify.errors }}</label>
        {% endif %}
        <div class="col-sm-12 row">
            <div class="col-8">
                {{ form.verify }}
            </div>
            <div class="col-4">
                <button id="id_btn_email" class="btn btn-light text-primary" type="button"
                        onclick="send_mail(this)">发送验证码
                </button>
            </div>
        </div>
    </div>
    <div class="form-group my-auto">
        <div class="col-sm-offset-2 col-sm-12 text-center">
            <button type="submit" class="btn btn-block btn-primary btn-lg">注册</button>
        </div>
    </div>
    <div class="container-fluid my-2">
        <a class="float-right btn-link" target="_self" href="{% url 'accounts:login' %}">已有账号，直接登录</a>
    </div>
{% endblock %}
{% block base_code_extend %}
    <script type="text/javascript">
        {# 时间 #}
        var curCount = 0;
        {# 计时器 #}
        var InterValObj;

        {# 验证码输入框显示 #}

        function SwitchVerifyBox() {
            var verify_box = $('#id_verify_box');
            h = verify_box.height();
            var index = parent.layer.getFrameIndex(window.name);
            if ($('#id_email').val()) {
                verify_box.show();
                $('#id_verify').attr('required', true);
                parent.layer.style(index, {height: 448 + h});
            } else {
                verify_box.hide();
                parent.layer.style(index, {height: 448});
            }
        }

        {# 窗口加载操作 #}
        window.onload = function () {
            SwitchVerifyBox();
        }

        {# 输入操作 #}
        $('input').on('input', function () {
            SwitchVerifyBox();
        });

        {# 邮箱变更操作 #}
        $('#id_email').on('change', function () {
            window.clearInterval(InterValObj);
            $('#id_btn_email').removeAttr("disabled"); //启用按钮
            $('#id_btn_email').text("发送验证码");
        });

        {# 设置倒计时 #}

        function SetRemainTimes(element, email) {
            if (curCount == 0) {
                window.clearInterval(InterValObj); //停止计时器
                element.removeAttr("disabled"); //启用按钮
                element.text("重新发送");
            } else {
                curCount--;
                element.text("重新发送(" + curCount + "s)");
            }
        };

        {# 发送邮件 #}

        function send_mail(e) {
            var element = $(e);
            var email = $('#id_email').val();
            var is_staff = false;
            if (email != "") {
                element.attr('disabled', true);
                var url = '{% url "accounts:send_email" %}';
                $.ajax({
                    url: url,
                    type: 'post',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: $('[name=csrfmiddlewaretoken]').val(),
                        email: email,
                        is_staff: is_staff,
                    },
                    cache: false,
                    success: function (JsonResponse) {
                        curCount = JsonResponse.timer;
                        {# 计时器 每秒使用SetRemainTimes刷新 #}
                        InterValObj = window.setInterval(SetRemainTimes, 1000, element, email);
                        layer.msg('验证码已发送');
                        element.text('重新发送(' + curCount + 's)');
                        return true;
                    },
                    error: function (HttpResponse) {
                        console.log('eeeee');
                        console.log(HttpResponse.responseText);
                        layer.msg(HttpResponse.responseText);
                        element.attr('disabled', false);
                        return false;
                    }
                });
            }
            return false;
        };
    </script>
{% endblock %}

templates/accounts/user_center_info.html
{% extends 'accounts/base/user_center_base.html' %}
{% load staticfiles %}
{% load accounts %}
{% load common_extras %}
{% block left_slider_subbox %}
    <div class="col col-md-2 col-lg-2">
        <a href="#" onclick='layer_open("{% url 'accounts:uc_edit_protrait' %}")'>
            <img class="img-thumbnail rounded-circle" width="150px" height="150px" src="{{ user.photo | is_protrait }}">
            <span class="btn btn-primary btn-block col-lg-7 col-md-12 col-sm-12" style="color: white;">修改头像</span>
        </a>
    </div>
{% endblock %}
{% block right_slider_subbox %}
    <div class="col col-md-8 col-lg-8">
        <table class="table table-hover">
            <caption style="caption-side:top;">
                <span>基本信息</span>
                <a class="float-right" style="color:blue;" href="{% url 'articles:list' user.username %}">个人主页<i class="layui-icon layui-icon-right"></i></a>
            </caption>
            <tbody>
            <tr>
                <td width="300px">账号</td>
                <td>{{ user.username | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">昵称</td>
                <td>{{ user.nick_name | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">姓名</td>
                <td>{{ user.name | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">性别</td>
                <td>{{ user.get_gender_display | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">生日</td>
                <td>{{ user.birth | default_if_none:_('') }}</td>
            </tr>
            </tbody>
        </table>

        <table class="table table-hover">
            <caption style="caption-side:top;">
                <span>详细信息</span>
                <a class="float-right" style="color:blue;" href="{% url 'accounts:uc_edit_info' %}">修改资料<i
                        class="layui-icon layui-icon-right"></i></a>
            </caption>
            <tbody>
            <tr>
                <td width="300px">电话</td>
                <td>{{ user.phone | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">邮箱</td>
                <td>{{ user.email | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">职业</td>
                <td>{{ user.profession | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">公司</td>
                <td>{{ user.company | default_if_none:_('') }}</td>
            </tr>
            <tr>
                <td width="300px">学校</td>
                <td>{{ user.school | default_if_none:_('') }}</td>
            </tr>
            </tbody>
        </table>
        <div class="table">
            <header style="caption-side:top;color: #6c757d;padding-top: .75rem;padding-bottom: .75rem;">
                <span>个人简介</span>
            </header>
            <hr>
            <blockquote class="layui-elem-quote">{{ user.intro | default_if_none:_('这家伙很懒，什么都没留下') }}</blockquote>

        </div>

    </div>
{% endblock %}
{% block base_code_extend %}
    <script type="text/javascript">
        function layer_open(url) {
            var index = layer.open({
                title: false,
                skin: 'demo-class',
                title: '修改头像',
                closeBtn: 1,
                resize: false,
                scrollbar: false,
                shadeClose: true,
                move: '.layui-layer-content',
                area: ["840px"],
                type: 2,
                offset: '20%',
                content: [url, 'no'],
                success: function () {
                    layer.iframeAuto(index);
                },
                end: function () {
                    window.parent.location.reload();
                }
            });
        };
        layui.use('laydate', function () {
            var laydate = layui.laydate;
            laydate.render({
                elem: '#id_birth',
                trigger: 'click',
                calendar: true,
                format: 'yyyy/MM/dd',
            });
        });
    </script>
{% endblock %}