SCSDN/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('blog.urls', namespace='blog')),
    re_path(r'accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'articles/', include('articles.urls', namespace='articles')),
    re_path(r'^mdeditor/', include('mdeditor.urls', namespace='mdeditor')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page=reverse_lazy('blog:index')), name='logout'),
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    path('reset/<uidb64>/<token>/', views.ResetPasswordView.as_view(), name='reset'),
    re_path(r'^change/$', views.ChangePasswordView.as_view(), name='change'),
    re_path(r'^send_email/$', views.SendEmailView.as_view(), name='send_email'),

    re_path(r'^user-center-info/$', views.UserCenterInfoView.as_view(), name='uc_info'),
    re_path(r'^user-center-collects/$', views.UserCenterCollectsView.as_view(), name='uc_collects'),
    re_path(r'^user-center-focus/$', views.UserCenterFocusView.as_view(), name='uc_focus'),
    re_path(r'^user-center-fans/$', views.UserCenterFansView.as_view(), name='uc_fans'),

    re_path(r'^user-center-photos/$', views.UserCenterPhotosView.as_view(), name='uc_photos'),
    re_path(r'^user-center-news/$', views.UserCenterNewsView.as_view(), name='uc_news'),

    re_path(r'^user-center-edit-protrait/$', views.UserCenterEditProtraitView.as_view(), name='uc_edit_protrait'),
    re_path(r'^user-center-edit-info/$', views.UserCenterEditInfoView.as_view(), name='uc_edit_info'),

    re_path(r'^accounts-manager-info/$', views.AccountsManagerInfoView.as_view(), name='am_info'),
]

apps/articles/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from articles import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^search/$', views.ArticleSearchView.as_view(), name='search'),
    re_path(r'^list/$', views.ArticleBackListView.as_view(), name='back'),
    re_path(r'^column/$', views.ArticleBackListView.as_view(), name='columns'),
    re_path(r'^tags/$', views.ArticleBackListView.as_view(), name='tags'),
    re_path(r'^comments/$', views.CommentsPostView.as_view(), name='comments'),
    re_path(r'^list/(?P<username>\w+)/$', views.ArticleListView.as_view(), name='list'),
    re_path(r'^show/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ArticleShowView.as_view(), name='show'),
    re_path(r'^actions/$', views.ArticleActionsView.as_view(), name='actions'),
    re_path(r'^post/$', views.ArticlePostView.as_view(), name='post')
]

apps/blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'blog'
urlpatterns = [
    # 首页展示
    re_path(r'^$', views.IndexView.as_view(), name='index'),
    re_path(r'^markdown$', views.MarkDownView.as_view(), name='markdown'),
    re_path(r'^verify$', views.DrawVerifyView, name='verify'),
]

templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">

    {% load staticfiles %}
    <title>{% block title %}{{ title }}-{{ site_title|default:_("这里输入站点标题") }}{% endblock %}</title>
    {% block base_icon_head %}
        <link rel="shortcut icon" href="{% static 'common/imgs/s-64x64.jpg' %}">
    {% endblock %}
    {% block base_css %}
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
        <link href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet">
        {#        <link rel="stylesheet" href="{% static 'mdeditor/css/editormd.css' %}" media="all">#}
    {% endblock %}
    {% block base_css_extend %}{% endblock %}
</head>
<body {% block base_body_style %}style="width: 100%;height: 100%;margin-bottom: 60px;" {% endblock %}>
{% block base_js_top %}{% endblock %}
<header>
    {% block header %}
        {% include "common/header.html" %}
    {% endblock %}
</header>
<main {% block main_class %}class="my-3"{% endblock %}>
    {% block content %}
        <div class="row container-fluid">
            {% block left_slider_box %}
                <div class="col col-md-2 col-lg-2">
                    {% block left_slider_body %}
                        <div class="bg-light" style="height: 100%">左侧边</div>
                    {% endblock %}
                </div>
            {% endblock %}
            {% block center_box %}
                <div class="col col-md-8 col-lg-8">
                    {% block center_body %}
                        <div>在这里输入正文</div>
                    {% endblock %}
                </div>
            {% endblock %}
            {% block right_slider_box %}
                <div class="col col-md-2 col-lg-2">
                    {% block right_slider_body %}
                        <div class="bg-light" style="height: 100%">右侧边</div>
                    {% endblock %}
                </div>
            {% endblock %}
        </div>
    {% endblock %}
</main>
<footer>
    {% block back_top %}
        {#        <a href="#">#}
        {#            <ul class="layui-fixbar" style="margin-bottom:80px">#}
        {#                <li class="layui-icon layui-fixbar-top" lay-type="top"#}
        {#                    style="display: list-item;">#}
        {#                </li>#}
        {#            </ul>#}
        {#        </a>#}
    {% endblock %}
    {% block footer %}
        {% include "common/footer.html" %}
    {% endblock %}
</footer>

{% block base_js_footer %}
    <script type="text/javascript" src="{% static 'common/js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'common/js/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'layui/layui.all.js' %}"></script>
    {#    <script type="text/javascript" src="{% static 'mdeditor/js/editormd.min.js' %}"></script>#}
{% endblock %}
{% block base_js_extend %}{#这里写入js代码#}{% endblock %}
{% block base_code %}{#这里写入js代码#}
    <script type="text/javascript">
        layui.use('util', function () {
            var util = layui.util;
            //执行
            util.fixbar({
                css: {'bottom': 80}
            });
        });
    </script>
{% endblock %}
{% block base_code_extend %}{#这里写入js代码#}{% endblock %}
</body>
</html>

templates/common/footer.html
<div class="text-muted bg-light fixed-bottom" style="width:100%;height: 60px;line-height: 60px;">
    <div class="container">
        <div>
            <span class="font-weight-bold">友情链接：</span>
            <a class="btn-link" href="https://docs.djangoproject.com/en/2.2/" target="_blank">Django官方文档</a>
            <a class="btn-link" href="http://fontawesome.dashgame.com/" target="_blank">FontAwesome字体官网</a>
            <a class="btn-link" href="https://fengyuanchen.github.io/cropper/" target="_blank">Cropper官网</a>
            <a class="btn-link" href="https://v2.bootcss.com/javascript.html#modals" target="_blank">Bootstrap官网</a>
            <a class="btn-link" href="https://www.layui.com/" target="_blank">Layui官网</a>
            <a class="btn-link" href="https://github.com/" target="_blank">Github</a>
            <a class="btn-link" href="https://www.django-rest-framework.org/" target="_blank">RestFramework官网</a>
        </div>
    </div>
</div>

templates/common/header.html
{% load staticfiles %}
{% load common_extras %}
{% load accounts %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blog:index' %}">
            {% block icon_navbar %}
                <img class="d-inline-block align-top"
                     src="{% static 'common/imgs/SCSDN.svg' %}" width="60px" height="24px">
            {% endblock %}
        </a>
        {# 窄屏收拢功能 #}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'blog:index' %}">
                        <span style="font-family:Impact;font-size: 16px;font-weight: bold;">首页</span>
                        <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span style="font-family:Impact;font-size: 16px;font-weight: bold;">博客</span>
                    </a>
                </li>
            </ul>
        </div>
        <form class="form-inline my-2 my-lg-0 mr-2" action="{% url 'articles:search' %}" method="post" target="_self">
            {% csrf_token %}
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="搜SCSDN" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
        </form>
        <div class="nav">
            <ul class="navbar-nav">
                <li class="nav-item my-2">
                    <a class="nav-link"
                       {% if user.is_authenticated %}
                       href="{% url 'articles:post' %}" target="_blank">
                       {% else %}
                       href="#" onclick='layer_open("{% url 'accounts:login' %}?next={% url 'articles:post' %}")'
                       {% endif %}
                        <span style="font-family:Impact;font-size: 16px;font-weight: bold;">
                            <i class="fa fa-paint-brush text-danger"></i>
                            写博客
                        </span>
                    </a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item my-2">
                        <a class="nav-link" href="#" onclick='layer_open("{% url 'accounts:login' %}")'>
                            <span style="font-family:Impact;font-size: 16px;font-weight: bold;">登录</span>
                        </a>
                    </li>
                    <li class="nav-item my-2">
                        <a class="nav-link" href="#" onclick='layer_open("{% url 'accounts:register' %}")'>
                            <span style="font-family:Impact;font-size: 16px;font-weight: bold;">注册</span>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item my-2">
                        <a class="nav-link" href="{% url 'accounts:uc_news' %}" target="_blank">
                            <span style="font-family:Impact;font-size: 16px;font-weight: bold;">
                                <i class="fa fa-envelope">
                                    消息
                                    <sup class="layui-badge layui-bg-orange">99+</sup>
                                </i>
                            </span>
                        </a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="rounded-circle" width="30px" height="30px" src="{{ user.photo | is_protrait }}"
                                 title="{{ user.username }}">
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'accounts:uc_info' %}">
                                <span>个人中心</span>
                            </a>
                            <a class="dropdown-item" href="{% url 'articles:back' %}">后台管理</a>
                            <a class="dropdown-item" href="{% url 'accounts:am_info' %}">账号设置</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:change' %}" target="_blank">修改密码</a>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">退出登录</a>
                            <a class="dropdown-item" href="#">帮助</a>
                        </div>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
    function layer_open(url) {
        var href = url.search('/?next=/')===-1 ? url : url + '?next=' + window.location.pathname
        var index = layer.open({
            title: false,
            skin: 'demo-class',
            closeBtn: 1,
            resize: false,
            scrollbar: false,
            shadeClose: true,
            move: '.layui-layer-content',
            area: ["400px"],
            type: 2,
            offset: '20%',
            content: [href, 'no'],
            success: function () {
                layer.iframeAuto(index);
            },
            end: function () {
                window.parent.location.reload();
            }
        });
    };
</script>

templates/common/layerui.html
{% extends 'common/base.html' %}

{% load staticfiles %}
{% load i18n static %}
{% load accounts %}

{% block header %}{% endblock %}
{% block content %}
    {% block form_container %}
        <div class="container-fluid my-2">
            <form class="form-horizontal mb-5" role="form" action="." method="post"
                  onsubmit="return onsubmitForm(this);">
                {% csrf_token %}
                {% block form_title %}
                    <p class="py-3 ml-2"
                       style="background:url('{% static "common/imgs/SCSDN.svg" %}') no-repeat left;background-size:70px;line-height:42px;">
                        <a class="text-primary" style="text-decoration: none;height: 32px;"
                           href="{% url 'blog:index' %}" target="_top">
                            <span style="color: black;font-size: 16px;padding-left: 75px;">
                                &middot; {{ site_header|default:_('用户名密码登录') }}
                            </span>
                        </a>
                    </p>
                {% endblock %}

                {% block form_errors %}
                    {% if user.is_authenticated %}
                        <p class="errornote errorlist  alert alert-danger mb-3">
                            {% blocktrans trimmed %}
                                You are authenticated as {{ user.username }} {{ form_ok }}, but are not authorized to
                                access this page. Would you like to login to a different account?
                            {% endblocktrans %}
                        </p>
                    {% endif %}
                {% endblock %}
                {% block form_body %}{% endblock %}
            </form>
        </div>
    {% endblock %}

{% endblock %}

{% block footer %}{% endblock %}
{% block base_code %}
    <script type="text/javascript">
        function GetFormData(e) {
            /* 获取全部表单数据，包含CSRF_TOKEN */
            var input_tags = e.getElementsByTagName('input');
            var next = window.location.search.split('=')[1] || window.parent.location.search.split('=')[1] || window.parent.location.href;
            var formData = {'next': next};
            for (var i = 0; i < input_tags.length; i++) {
                var input_tag = input_tags[i];
                if (input_tag.type == 'checkbox') {
                    formData[input_tag.name] = input_tag.checked;
                } else {
                    formData[input_tag.name] = input_tag.value;
                }
            }
            return formData;
        };

        function RefreshVerify(id, src) {
            id = id || 'id_login_verify_img';
            if ($("#" + id)) {
                src = src || ({{ MEDIA_URL }} +"verifys/verify.png?");
                $.ajax({
                    type: 'get',
                    dataType: 'json',
                    url: '{% url "blog:verify" %}',
                    success: function () {
                        $("#" + id).attr('src', src + Math.random());
                    }
                });
            }
        }

        function onsubmitForm(e) {
            /* ajax表单提交 */
            var formData = GetFormData(e);
            {#console.log(formData);#}
            var index = parent.layer.getFrameIndex(window.name);
            var url = window.location.pathname;
            $.ajax({
                url: url,
                type: 'post',
                dataType: 'json',
                data: formData,
                cache: false,
                success: function (responseData) {
                    parent.layer.close(index);
                    layer.msg('操作成功，即将跳转！');
                    /* 成功跳转 */
                    window.parent.location.href = responseData.success_url;
                    return false;
                },
                error: function (responseData) {
                    /* 失败重新渲染窗口 */
                    // console.log(responseData.responseText);
                    window.document.write(responseData.responseText);
                    window.document.close();
                    RefreshVerify();
                    layer.msg('操作失败，请稍后再试');
                    return false;
                }
            });
            return false;
        }
    </script>
{% endblock %}
{% block base_code_extend %}{% endblock %}

templates/common/paginator.html
{% load staticfiles %}
{% load common_extras %}
{% if num_pages > 1 %}
    <nav aria-label="Page navigation" style="position: absolute;bottom: -40px">
        <ul class="pagination">
            <li class="page-item {% if not page.has_previous %}disabled{% endif %}">
                <a class="page-link" tabindex="-1" href="javascript:;"
                   onclick="onclicked(
                           {% if page.has_previous %}{{ page.previous_page_number }}{% else %}{{ page.number }}{% endif %})">
                    上一页
                </a>
            </li>
            {% for number in pages %}
                <li class="page-item {% if page.number == number %}active{% endif %}">
                    <a class="page-link" href="javascript:;" onclick="onclicked({{ number }})">
                        {{ number }}
                        {% if page.number == number %}<span class="sr-only">(current)</span>{% endif %}
                    </a>
                </li>
            {% endfor %}
            <li class="page-item {% if not page.has_next %}disabled{% endif %}">
                <a class="page-link" href="javascript:;"
                   onclick="onclicked(
                           {% if page.has_next %}{{ page.next_page_number }}{% else %}{{ page.number }}{% endif %})">
                    下一页
                </a>
            </li>
        </ul>
    </nav>
{% endif %}
<script>
    function onclicked(number) {
        // 锚点处理
        var anchor = location.hash;
        var search = "?page=" + number.toString();
        var href = location.href;
        var host = href.substring(0, href.indexOf(location.search));
        location.href = host + search + anchor;
    }
</script>