SCSDN/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('blog.urls', namespace='blog')),
    re_path(r'accounts/', include('accounts.urls', namespace='accounts')),
    re_path(r'articles/', include('articles.urls', namespace='articles')),
    re_path(r'^mdeditor/', include('mdeditor.urls', namespace='mdeditor')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/urls.py
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    re_path(r'^login/$', views.LoginView.as_view(), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(next_page=reverse_lazy('blog:index')), name='logout'),
    re_path(r'^register/$', views.RegisterView.as_view(), name='register'),
    path('reset/<uidb64>/<token>/', views.ResetPasswordView.as_view(), name='reset'),
    re_path(r'^change/$', views.ChangePasswordView.as_view(), name='change'),
    re_path(r'^send_email/$', views.SendEmailView.as_view(), name='send_email'),

    re_path(r'^user-center-info/$', views.UserCenterInfoView.as_view(), name='uc_info'),
    re_path(r'^user-center-collects/$', views.UserCenterCollectsView.as_view(), name='uc_collects'),
    re_path(r'^user-center-focus/$', views.UserCenterFocusView.as_view(), name='uc_focus'),
    re_path(r'^user-center-fans/$', views.UserCenterFansView.as_view(), name='uc_fans'),

    re_path(r'^user-center-photos/$', views.UserCenterPhotosView.as_view(), name='uc_photos'),
    re_path(r'^user-center-news/$', views.UserCenterNewsView.as_view(), name='uc_news'),

    re_path(r'^user-center-edit-protrait/$', views.UserCenterEditProtraitView.as_view(), name='uc_edit_protrait'),
    re_path(r'^user-center-edit-info/$', views.UserCenterEditInfoView.as_view(), name='uc_edit_info'),

    re_path(r'^accounts-manager-info/$', views.AccountsManagerInfoView.as_view(), name='am_info'),
]

apps/articles/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.urls import re_path, reverse_lazy, path
from django.contrib.auth import views as auth_views

from articles import views

app_name = 'articles'

urlpatterns = [
    re_path(r'^search/$', views.ArticleSearchView.as_view(), name='search'),
    re_path(r'^list/$', views.ArticleBackListView.as_view(), name='back'),
    re_path(r'^column/$', views.ArticleBackListView.as_view(), name='columns'),
    re_path(r'^tags/$', views.ArticleBackListView.as_view(), name='tags'),
    re_path(r'^comments/$', views.CommentsPostView.as_view(), name='comments'),
    re_path(r'^list/(?P<username>\w+)/$', views.ArticleListView.as_view(), name='list'),
    re_path(r'^show/(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ArticleShowView.as_view(), name='show'),
    re_path(r'^actions/$', views.ArticleActionsView.as_view(), name='actions'),
    re_path(r'^post/$', views.ArticlePostView.as_view(), name='post')
]

apps/articles/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from django import forms
from django.db.models import Q
from django.forms import widgets
from articles.models import Articles, ArticleComments


# TODO：搜索表单
class ArticleSearchForm(forms.Form):
    search = forms.CharField(max_length=256, label="搜索内容", required=False, widget=widgets.TextInput(
        attrs={
            'type': 'search',
            'class': 'form-control mr-sm-2',
            'aria-label': 'Search',
            'placeholder': '搜SCSDN'
        }))

    def clean_search(self):
        search = self.cleaned_data['search'].strip()
        if search:
            articles = Articles.objects.filter(
                Q(author__username__icontains=search) |
                Q(author__nick_name__icontains=search) |
                Q(title__icontains=search) |
                Q(body__contains=search) |
                Q(column__body__contains=search) |
                Q(tags__body__contains=search))
        else:
            articles = Articles.objects.filter(status='1')
        if articles:
            return articles.order_by('-update')
        else:
            raise forms.ValidationError('搜索结果为空')


class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = ('title', 'body')

        widgets = {
            'title': widgets.TextInput(attrs={
                'class': 'form-control',
                'placeholder': '输入文章标题'
            })}


class ArticleCommentsForm(forms.ModelForm):
    # 此处注意 author指定的to_field字段为username
    class Meta:
        model = ArticleComments
        fields = ('author', 'article', 'body',)

apps/articles/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.http import JsonResponse, HttpResponseForbidden, Http404, HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth import get_user_model, views as auth_views
from django.views import generic

from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.db.models import Q

import re

from accounts.views import LoginRequiredPostMixin
from articles.models import Articles
from common.utils.paginator import paginator

from articles.forms import ArticleSearchForm, ArticlePostForm, ArticleCommentsForm

UserModel = get_user_model()


# Create your views here.
class ArticleBackListView(LoginRequiredPostMixin, auth_views.TemplateView):
    template_name = 'articles/back_stage_articles.html'
    extra_context = {"title": "博客管理", 'site_title': 'SCSDN博客'}

    def get(self, request, *args, **kwargs):
        articles = request.user.articles.all().order_by('-top')
        publics = articles.filter(status='1')
        privates = articles.filter(status='2')
        drafts = articles.filter(status='3')
        deleteds = articles.filter(status='4')
        self.extra_context.update(paginator(request, articles))
        self.extra_context.update({
            'total': articles.count,
            'publics': publics,
            'privates': privates,
            'drafts': drafts,
            'deleteds': deleteds,
        })
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        layid = request.POST.get('layid', '1')
        articles = request.user.articles.all().order_by('-top')
        response_context = {'layid': layid}
        if str(layid) != '0':
            articles = articles.filter(status=layid).order_by('-top')
        response_context.update(paginator(request, articles))
        return render(request, 'articles/base/article_intro_list.html', response_context)


class ArticleListView(auth_views.TemplateView):
    template_name = 'articles/article_list_author.html'
    extra_context = {'site_title': 'SCSDN博客'}

    def get(self, request, *args, **kwargs):
        username = kwargs['username']
        author = UserModel._default_manager.get(username=username)

        if username == request.user.username:
            articles = author.articles.all().order_by('-top')
        else:
            articles = author.articles.filter(status='1').order_by('-top')
        self.extra_context.update({
            'title': '{0}的博客'.format(username),
            'author': author})

        self.extra_context.update(paginator(request, articles))
        return super().get(request, *args, **kwargs)


class ArticleShowView(auth_views.TemplateView):
    template_name = 'articles/article_show.html'
    extra_context = {'site_title': 'SCSDN博客'}

    def get(self, request, *args, **kwargs):
        article = get_object_or_404(Articles, id=kwargs['id'], slug=kwargs['slug'])
        self.extra_context.update({"title": article.title, 'article': article})
        return super().get(request, *args, **kwargs)


class ArticleActionsView(LoginRequiredPostMixin, generic.View):
    def post(self, request, *args, **kwargs):
        method = request.POST.get('method', '')
        option = request.POST.get('option', '')
        secondOption = request.POST.get('secondOption', '')
        if not (method and option):
            return JsonResponse({'status': 'not ok'})

        if method.lower() == 'settop':
            article = Articles.objects.get(id=int(option))
            article.set_top()
        elif method.lower() == 'setallowreply':
            article = Articles.objects.get(id=int(option))
            article.set_allowreply()
        elif method.lower() == 'delete':
            article = Articles.objects.get(id=int(option))
            article.delete()
        elif method.lower() == 'recycle':
            article = Articles.objects.get(id=int(option))
            article.set_status('4')
        elif method.lower() == 'drafts':
            article = Articles.objects.get(id=int(option))
            article.set_status('3')
        elif method.lower() == 'focus':
            print('focus')
            followed = UserModel._default_manager.get(id=int(option))
            followed.set_fans(request.user)
        elif method.lower() == 'unfollow':
            follower = UserModel._default_manager.get(id=int(option))
            request.user.set_unfollow(follower)
        elif method.lower() == 'favorite':
            article = Articles.objects.get(id=int(option))
            article.add_favorite(self.request.user)
        elif method.lower() == 'disfavorite':
            article = Articles.objects.get(id=int(option))
            article.del_favorite(self.request.user)
        elif method.lower() == 'like':
            article = Articles.objects.get(id=int(option))
            article.add_like(self.request.user)
        elif method.lower() == 'unlike':
            article = Articles.objects.get(id=int(option))
            article.del_like(self.request.user)
        else:
            return JsonResponse({'status': 'not ok'})

        return JsonResponse({'status': 'ok'})


class ArticleSearchView(auth_views.TemplateView):
    template_name = 'blog/index.html'
    extra_context = {'title': 'SCSDN', 'site_title': '专业IT技术社区'}

    def post(self, request, *args, **kwargs):
        search = request.POST.get('search')
        if search:
            self.extra_context.update({'title': search, 'site_title': 'SCSDN搜索'})
        form = ArticleSearchForm(request.POST)
        articles = {} if not form.is_valid() else form.cleaned_data['search']
        if not articles:
            self.extra_context.update({'message': '没检索到需要搜索的内容！'})
        self.extra_context.update(paginator(request, articles))
        return super().get(request, *args, **kwargs)


class ArticlePostView(LoginRequiredPostMixin, auth_views.FormView):
    template_name = 'articles/article_edit.html'
    extra_context = {'title': '写博客', 'site_title': 'SCSDN博客'}
    form_class = ArticlePostForm

    def get(self, request, *args, **kwargs):
        id = request.GET.get('id', '')
        article = '' if not id.isdigit() else Articles.objects.get(id=int(id))
        if article:
            self.initial = {'title': article.title, 'body': article.body}
        self.extra_context.update({'article': article})
        if not article or self.request.user == article.author:
            return super().get(request, *args, **kwargs)
        else:
            return HttpResponseForbidden()

    def form_valid(self, form):
        id = self.request.POST.get('id', self.request.GET.get('id', ''))
        article = None if not id.isdigit() else Articles.objects.get(id=int(id))
        if article and self.request.user == article.author:
            article.title = form.cleaned_data['title']
            article.body = form.cleaned_data['body']
            article.save()
        else:
            new_article = form.save(commit=False)
            new_article.author = self.request.user
            new_article.save()
        self.success_url = reverse('articles:list', kwargs={'username': self.request.user.username})
        return super().form_valid(form)


class CommentsPostView(LoginRequiredPostMixin, generic.View):
    def post(self, request, *args, **kwargs):
        form = ArticleCommentsForm(request.POST)
        id = request.POST.get('article')
        slug = Articles.objects.get(id=int(id)).slug
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse_lazy('articles:show', kwargs={'id': id, 'slug': slug}))

templates/articles/base/article_intro_list.html
{% load staticfiles %}
<style>
    .list-item-title {
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: row;
        flex-direction: row;
        -ms-flex-pack: start;
        justify-content: flex-start;
    }

    .list-item-title-text {
        font-size: 18px;
        color: #4f4f4f;
        margin-bottom: 0;
    }

    .list-item-tag {
        font-size: 12px;
        padding: 0 8px;
        height: 24px;
        line-height: 24px;
        margin-right: 0.5rem;
        white-space: nowrap;
        color: red;
        border: 1px solid #e9e9e9;
    }

    .list-item-info-operate {
        color: #349EDF;
        cursor: pointer;
        font-size: 12px;
    }

    .list-item-info-operate > a {
        text-decoration: none;
        padding: 0px .5rem;
        border-right: 1px solid #e9e9e9;
        color: #349EDF;
    }
</style>
<div class="list-group">
    {% for article in articles %}
        <div class="list-group-item">
            <div class="list-item-title">
                {% if article.status == '4' %}
                    <span class="list-item-tag">已删除</span>
                {% elif article.status == '3' %}
                    <span class="list-item-tag">草稿</span>
                {% else %}
                    {% if article.top %}<span class="list-item-tag">置顶</span>{% endif %}
                    {% if article.status == '2' %}<span class="list-item-tag">私密</span>{% endif %}
                {% endif %}
                <a class="list-item-title-text" href="{% url 'articles:post' %}?id={{ article.id }}">{% if article.status == '4' %}<del>{{ article.title }}</del>{% else %}{{ article.title }}{% endif %}</a>
            </div>
            <div class="list-item-info">
                <span class="mt-3 mx-2 float-left" style="font-size: 12px;color: #999;">
                    <span><i class="fa fa-clock-o mr-1"></i>{{ article.created }}</span>
                    <span><i class="layui-icon layui-icon-read  ml-3 mr-1"></i>{{ article.likes.count }}</span>
                    <span><i class="fa fa-commenting-o ml-3 mr-1"></i>{{ article.comments.count }}</span>
                    <span><i class="fa fa-heart ml-3 mr-1"></i>{{ article.likes.count }}</span>
                </span>
                <span class="list-item-info-operate mt-3 mx-2 float-right article-action">
                    <a href="{{ article.get_absolute_url }}">查看</a>
                    {% if article.status == '4' %}
                        <a data-method="drafts" data-option="{{ article.id }}">回收至草稿箱</a>
                        <a style="color: #CA0C16;border-right:none;" data-method="delete"
                           data-option="{{ article.id }}">彻底删除</a>
                    {% elif article.status == '3' %}
                        <a style="color: #CA0C16;border-right:none;" data-method="recycle"
                           data-option="{{ article.id }}">删除</a>
                    {% else %}
                        <a data-method="setAllowreply" data-option="{{ article.id }}">
                            {% if article.allowreply %}禁止评论{% else %}允许评论{% endif %}
                        </a>
                        <a data-method="setTop" data-option="{{ article.id }}">
                            {% if article.top %}取消置顶{% else %}置顶{% endif %}
                        </a>
                        <a style="color: #CA0C16;border-right:none;" data-method="recycle"
                           data-option="{{ article.id }}">删除</a>
                    {% endif %}
                </span>
            </div>
        </div>
    {% empty %}
        <div class="no-data d-flex flex-column justify-content-center align-items-center"
             style="margin-top:100px;padding-bottom:100px;">
            <div style="opacity: 0.8;">
                <img src="{% static 'common/imgs/empty.svg' %}" width="120px" height="73px">
                <h4 class="text-center"
                    style="font-size: 16px;color: #6B6B6B;font-weight: bold;letter-spacing: 2px;padding: 15px;">
                    空空如也
                </h4>
            </div>
            {% if layid != '4' %}
                <a href="{% url 'articles:post' %}" target="_blank">
                    <button style="width: 300px;height: 40px;background: #CA0C16;border-radius: 4px;font-size: 18px;color: #FFFFFF; margin-top: 15px;"
                            type="button" class="btn btn-outline-danger">
                        写博客
                    </button>
                </a>
            {% endif %}
        </div>
    {% endfor %}
    {% include 'common/paginator.html' %}
</div>

templates/articles/base/article_show_leftslider.html
{% load staticfiles %}
{% load common_extras %}

<style>
    .block_box {
        padding: 16px 16px;
        padding-bottom: 16px;
        border-bottom: 1px solid #e3e3e3;
    }


    .author {
        isplay: inline-block;
        color: #3d3d3d;
        font-weight: 700;
        max-width: 150px;
        max-height: 66px;
        overflow: hidden;
        word-wrap: break-word;
        margin-left: 10px;
    }

    .count {
        font-weight: 700;
    }

    dt, dt > a {
        color: rgba(0, 0, 0, .5);
        margin-bottom: 10px;
        margin-left: -5px;
        padding-right: 5px;
        font-family: 'Microsoft YaHei', 'SF Pro Display', Roboto, Noto, Arial, 'PingFang SC', sans-serif;
    }

    dd, dd > a {
        font-weight: 700;
        margin-left: -5px;
        padding-right: 5px;
        font-family: 'Microsoft YaHei', 'SF Pro Display', Roboto, Noto, Arial, 'PingFang SC', sans-serif;
    }

    a.border-danger:hover {
        background-color: lightcyan;
    }
</style>
<div style="box-shadow: 0 2px 4px 0 rgba(0,0,0,0.05);">
    {% if article %}
        <div class="block_box">
            <a href="{% url 'articles:list'  article.author.username %}" style="text-decoration: none;">
                <span>
                    <img class="img-thumbnail rounded-circle" width="48px" height="48px"
                         src="{{ article.author.photo|is_protrait }}">
                </span>
                <span class="author">{{ article.author.nick_name | default_if_none:article.author.username }}</span>
            </a>
            <span class="article-action">
            {% if user and user == article.author %}
                <a class="btn btn-sm btn-link float-right mt-2" href="{% url 'accounts:uc_info' %}">个人中心</a>
            {% elif user and article.author.get_fans|include:user %}
                <a class="btn btn-sm border-danger text-danger float-right mt-2"
                   {% if user.is_authenticated %}data-method="unfollow" data-option="{{ article.author.id }}"
                   {% else %}onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>取消关注</a>
            {% else %}
                <a class="btn btn-sm border-danger text-danger float-right mt-2"
                   {% if user.is_authenticated %}data-method="focus" data-option="{{ article.author.id }}"
                   {% else %}onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>关注</a>
            {% endif %}
            </span>
        </div>
        <div class="d-flex block_box">
            <dl class="text-center" style="width: 100%;">
                <dt><a href="#" style="text-decoration: none;">原创</a></dt>
                <dd>
                    <a href="#" style="text-decoration: none;">
                        <span class="count">{{ article.author.get_origin.count }}</span>
                    </a>
                </dd>
            </dl>
            <dl class="text-center" id="fanBox" style="width: 100%;color: inherit;">
                <dt>粉丝</dt>
                <dd>
                <span class="count" id="fans">{{ article.author.fans.count|default:'0' }}
                </span>
                </dd>
            </dl>
            <dl class="text-center" style="width: 100%;color: inherit;">
                <dt>喜欢</dt>
                <dd><span class="count">{{ article.author.focus.count|default:'0' }}</span></dd>
            </dl>
            <dl class="text-center" style="width: 100%;color: inherit;">
                <dt>评论</dt>
                <dd><span class="count">{{ article.author.comments.count|default:'0' }}</span></dd>
            </dl>
        </div>
    {% elif author %}
        <div class="block_box">
            <a href="{% url 'articles:list' author.username %}" style="text-decoration: none;">
                <span>
                    <img class="img-thumbnail rounded-circle" width="48px" height="48px"
                         src="{{ author.photo|is_protrait }}">
                </span>
                <span class="author">{{ author.nick_name | default_if_none:author.username }}</span>
            </a>
            <span class="article-action">
            {% if user and user == author %}
                <a class="btn btn-sm btn-link float-right mt-2" href="{% url 'accounts:uc_info' %}">个人中心</a>
            {% elif user and author.get_fans|include:user %}
                <a class="btn btn-sm border-danger text-danger float-right mt-2"
                   {% if user.is_authenticated %}data-method="unfollow" data-option="{{ author.id }}"
                   {% else %}onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>取消关注</a>
            {% else %}
                <a class="btn btn-sm border-danger text-danger float-right mt-2"
                   {% if user.is_authenticated %}data-method="focus" data-option="{{ author.id }}"
                   {% else %}onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>关注</a>
            {% endif %}
            </span>
        </div>
        <div class="d-flex block_box">
            <dl class="text-center" style="width: 100%;">
                <dt><a href="#" style="text-decoration: none;">原创</a></dt>
                <dd>
                    <a href="#" style="text-decoration: none;">
                        <span class="count">{{ author.get_origin.count }}</span>
                    </a>
                </dd>
            </dl>
            <dl class="text-center" id="fanBox" style="width: 100%;color: inherit;">
                <dt>粉丝</dt>
                <dd>
                <span class="count" id="fans">{{ author.fans.count|default:'0' }}
                </span>
                </dd>
            </dl>
            <dl class="text-center" style="width: 100%;color: inherit;">
                <dt>收藏</dt>
                <dd><span class="count">{{ author.article_favorites.count|default:'0' }}</span></dd>
            </dl>
            <dl class="text-center" style="width: 100%;color: inherit;">
                <dt>评论</dt>
                <dd><span class="count">{{ author.comments.count|default:'0' }}</span></dd>
            </dl>
        </div>
    {% endif %}
</div>

templates/articles/base/article_show_rightslider.html
{% load staticfiles %}
{% load common_extras %}

<style>
    .count {
        font-weight: 700;
    }

    dt, dt > a {
        color: rgba(0, 0, 0, .5);
        margin-bottom: 10px;
        margin-left: -5px;
        padding-right: 5px;
        font-family: 'Microsoft YaHei', 'SF Pro Display', Roboto, Noto, Arial, 'PingFang SC', sans-serif;
    }

    dd, dd > a {
        font-weight: 700;
        margin-left: -5px;
        padding-right: 5px;
        font-family: 'Microsoft YaHei', 'SF Pro Display', Roboto, Noto, Arial, 'PingFang SC', sans-serif;
    }

    a.border-danger:hover {
        background-color: lightcyan;
    }
</style>
<div class="col col-md-3 col-lg-3">
    <div class="d-flex py-2 mb-2 article-action" style="box-shadow: 0 2px 4px 0 rgba(0,0,0,0.05);">
        <dl class="text-center" style="width: 100%;">
            <dt>{% if article.likes.all|include:user %}
                <a href="#" data-method="unlike" data-option="{{ article.id }}" style="text-decoration: none;">
                    <span class="mr-1">点赞</span><i class="fa fa-thumbs-up"></i></a>
            {% else %}
                <a href="#" data-method="like" data-option="{{ article.id }}" style="text-decoration: none;">
                    <span class="mr-1">点赞</span><i class="fa fa-thumbs-o-up"></i></a>
            {% endif %}
            </dt>
            <dd>
                <a href="#" style="text-decoration: none;">
                    <span class="count">{{ article.likes.count }}</span>
                </a>
            </dd>
        </dl>
        <dl class="text-center" style="width: 100%;color: inherit;">
            <dt>{% if article.favorites.all|include:user %}
                <a href="#" data-method="disfavorite" data-option="{{ article.id }}" style="text-decoration: none;">
                    <span class="mr-1">收藏</span><i class="fa fa-bookmark"></i></a>
            {% else %}
                <a href="#" data-method="favorite" data-option="{{ article.id }}" style="text-decoration: none;">
                    <span class="mr-1">收藏</span><i class="fa fa-bookmark-o"></i></a>
            {% endif %}
            </dt>
            <dd>
                <span class="count">{{ article.favorites.count|default:'0' }}
                </span>
            </dd>
        </dl>
        <dl class="text-center" style="width: 100%;color: inherit;">
            <dt><a href="#comment-post">评论</a></dt>
            <dd><span class="count">{{ article.comments.count|default:'0' }}</span></dd>
        </dl>
        <dl class="text-center" style="width: 100%;color: inherit;">
            <dt>访问</dt>
            <dd><span class="count">{{ article.author.focus.count|default:'0' }}</span></dd>
        </dl>
    </div>

    <form id="comment-post" class="layui-form pb-2" action="{% url 'articles:comments' %}" method="post">
        {% csrf_token %}
        <div class="layui-form-item">
            <input name="author" class="sr-only" value="{{ user.username }}">
        </div>
        <div class="layui-form-item">
            <input name="article" class="sr-only" value="{{ article.id }}">
        </div>
        <div class="layui-form-item layui-form-text">
            <textarea name="body" class="layui-textarea" placeholder="想发表点什么看法"></textarea>
        </div>
        <div class="layui-form-item">
            <a {% if user.is_authenticated %}href="{% url 'articles:list' user.username %}"
               {% else %}onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>
                <img class="rounded-circle" src="{{ user.photo|is_protrait }}" width="32px"
                     title="{% if user.is_authenticated %}{{ user.nick_name|default:user.username }}{% else %}
                Anonymous{% endif %}">
            </a>
            <button class="layui-btn float-right" {% if user.is_authenticated %}type="submit"{% else %}type="button"
                    onclick='layer_open("{% url 'accounts:login' %}")'{% endif %}>发表评论
            </button>
        </div>
    </form>
    {% if article.comments.count > 0 %}
    <fieldset class="layui-elem-field">
        <legend>评论内容</legend>
        <div class="layui-field-box">
            <ul class="list-group">
                {% for comment in article.comments.all %}
                    <li class="list-group-item clearfix my-1">
                        <span>
                            <a class="card-link" href="{% url 'articles:list' comment.author.username %}">
                            <img class="rounded-circle" src="{{ comment.author.photo|is_protrait }}" width="24px">
                            <span class="text-primary">{{ comment.author.nick_name|default:comment.author.username }}：</span>
                            </a>
                        </span>
                        <p class="layui-text text-muted" style="text-indent:2em;word-break: break-word;">
                            {{ comment.body }}
                            <span class="article-action float-right">
                                <a class="text-primary">查看回复</a>
                                {% if comment.author == user or article.author == user %}<a class="text-primary">删除</a>{% endif %}
                                <a class="text-primary">举报</a>
                                <a class="text-primary">回复</a>
                            </span>
                        </p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </fieldset>
    {% endif %}
</div>

templates/articles/base/back_stage_base.html
{% extends 'common/base.html' %}
{% block left_slider_body %}
    {% include 'articles/base/back_stage_leftslider.html' %}
{% endblock %}
{% block center_box %}
    <div class="col col-md-10 col-lg-10">
        {% block center_body %}{% endblock %}
    </div>
{% endblock %}
{% block right_slider_box %}{% endblock %}

templates/articles/base/back_stage_leftslider.html
{% load staticfiles %}
{% load accounts %}
<div class="py-5 mt-3">
    <ul class="layui-nav layui-nav-tree layui-bg-cyan">
        <li class="layui-nav-item">
            <a {% if request.path|is_ac_back %}class="layui-this"{% else %}class=""{% endif %}
               href="{% url 'articles:back' %}">博客管理</a>
        </li>
        <li class="layui-nav-item">
            <a {% if request.path|is_ac_columns %}class="layui-this"{% else %}class=""{% endif %}
               href="{% url 'articles:columns' %}">栏目管理</a>
        </li>
        <li class="layui-nav-item">
            <a {% if request.path|is_ac_tags %}class="layui-this"{% else %}class=""{% endif %}
               href="{% url 'articles:tags' %}">标签管理</a>
        </li>
        <li class="layui-nav-item">
            <a {% if request.path|is_ac_comments %}class="layui-this"{% else %}class=""{% endif %}
               href="{% url 'articles:comments' %}">评论管理</a>
        </li>
    </ul>
</div>